/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * JSON schema for core NCBI collection in RCSB Data Warehouse.
 *
 */
export interface ProteinSeqeunceAlignmentJson {
  target_id?: string;
  /**
   * Target sequence region
   */
  target_sequence?: string;
  /**
   * Alignment scores
   */
  coverage?: {
    target_coverage: number;
    query_coverage: number;
    target_length: number;
    query_length: number;
  };
  /**
   * Aligned sequence regions
   */
  aligned_regions?: {
    /**
     * Target sequence start position
     */
    target_begin: number;
    /**
     * Query sequence start position
     */
    query_begin: number;
    /**
     * Target sequence start position
     */
    target_end: number;
    /**
     * Query sequence end position
     */
    query_end: number;
    exon_shift?: number[];
  }[];
  orientation?: number;
}
