/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AlignmentResponse {
  query_sequence?: string;
  target_alignment?: TargetAlignment[];
}
/**
 * JSON schema for core NCBI collection in RCSB Data Warehouse.
 *
 */
export interface TargetAlignment {
  target_id?: string;
  /**
   * Target sequence region
   */
  target_sequence?: string;
  coverage?: Coverage;
  /**
   * Aligned sequence regions
   */
  aligned_regions?: AlignedRegion[];
  orientation?: number;
}
/**
 * Alignment scores
 */
export interface Coverage {
  target_coverage: number;
  query_coverage: number;
  target_length: number;
  query_length: number;
}
/**
 * Aligned region
 */
export interface AlignedRegion {
  /**
   * Target sequence start position
   */
  target_begin: number;
  /**
   * Query sequence start position
   */
  query_begin: number;
  /**
   * Target sequence start position
   */
  target_end: number;
  /**
   * Query sequence end position
   */
  query_end: number;
  exon_shift?: number[];
}
