/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Annotation {
  /**
   * A description for the feature.
   */
  description?: string;
  /**
   * An identifier for the feature.
   */
  feature_id?: string;
  /**
   * A name for the feature.
   */
  name?: string;
  /**
   * A type or category of the feature.
   */
  type?: string;
  /**
   * The value for the feature.
   */
  value?: number;
  positions?: {
    /**
     * An identifier for the monomer at which this segment of the feature begins.
     */
    begin?: number;
    /**
     * An identifier for the monomer at which this segment of the feature ends.
     */
    end?: number;
    gaps?: {
      begin?: number;
      end?: number;
      [k: string]: any;
    }[];
    open_begin?: boolean;
    open_end?: boolean;
    /**
     * The value for the feature at this monomer.
     */
    value?: number;
  }[];
}
