/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AnnotationFeatures {
  target_id?: string;
  source?: "PDB_INSTANCE" | "PDB_ENTITY" | "UNIPROT";
  features?: Feature[];
}
/**
 * JSON schema for core NCBI collection in RCSB Data Warehouse.
 *
 */
export interface Feature {
  /**
   * A description for the feature.
   */
  description?: string;
  /**
   * An identifier for the feature.
   */
  feature_id?: string;
  /**
   * A name for the feature.
   */
  name?: string;
  /**
   * A type or category of the feature.
   */
  type?: string;
  /**
   * The value for the feature.
   */
  value?: number;
  feature_positions?: FeaturePosition[];
}
export interface FeaturePosition {
  /**
   * An identifier for the monomer at which this segment of the feature begins.
   */
  beg_seq_id?: number;
  /**
   * An identifier for the monomer at which this segment of the feature ends.
   */
  end_seq_id?: number;
  gaps?: Gap[];
  open_begin?: boolean;
  open_end?: boolean;
  /**
   * The value for the feature at this monomer.
   */
  value?: number;
}
export interface Gap {
  begin?: number;
  end?: number;
  [k: string]: any;
}
